module Task45

(*
 * Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 *)

let run = 
    let set = Set.ofList [2I..140000I]
    let trigonals = set |> Set.map (fun n -> n * (n + 1I) / 2I) 
    let pentagonals = set |> Set.map (fun n -> n * (3I * n - 1I) / 2I)  
    let hexagonals = set |> Set.map (fun n -> n * (2I * n - 1I))   

    trigonals
    |> Set.intersect pentagonals
    |> Set.intersect hexagonals
    |> printfn "%A"